hash-format = "sha256"

[[files]]
file = "config/betterdays-common.toml"
hash = "235351026dadd2d5ea2b058ab6310b1092f6dec7d7226dcdade97d151c6d4256"

[[files]]
file = "config/sophisticatedcore-common.toml"
hash = "e25e58d7d028b491ef2cb2b3c0dbf5a43afda0ef85d871a896ef08ecdcda1330"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "8a9a92db01486e4f8d3a7370a6cbf6e59a12d1ef15c24b375ebce75500e78afc"
metafile = true

[[files]]
file = "mods/accessories-cc-layer.pw.toml"
hash = "70b60dc87321c41bbb217d23d97beb7950d0cf61b6a2bc48e8f1a7ee6d9af784"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "83e4c486594e796b86e6d44f00626617857f60dcb5da16660e17cdf140215811"
metafile = true

[[files]]
file = "mods/advanced-netherite.pw.toml"
hash = "46a3e89d8b17ef1564d323cb24a8ee8dbaf96d7b07324379d5bb0858e9996212"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "29ee18f6cc9ff4948029892820bd83dd645580691e79bae2192711d54bc38e89"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "5724ca10bd6d37de46834ab762a46f9ce09175f0a4fa0e2ab633846067940c03"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "66a565347d7180cccfa48e0601093e901eec74e4a5b56eed67cd32ca3c0cc4cd"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/better-village.pw.toml"
hash = "528153829c3c3f7d5f4cab313bb0ddd0755779dbce26d4c7080d2ab5754b1ca8"
metafile = true

[[files]]
file = "mods/betterdays.pw.toml"
hash = "de47f720da923c1c601bd184f40379e8dd6db17619ec8705c8f885b70b060bae"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "c9aca350959a8936b054c7164fb55d789ab1e0d38cff2af48b78f70af2bc0c6d"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
hash = "6789ad2958a2dc2ea1b45c3eae624f4535eac9475b03c3f496fde07debbcb178"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "992b0dca9683f225fc774d779762d18a009f2d82b9d051e7c0b55a33a95d9238"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "c899acdc322ab52800a6e305a16427297f411c1c39d97983be96e8b6a34e157c"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "00a6a59105f7bc307cf04c1dfb129b300c29a4cb550a5825cacdb54dbc598c68"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "1e35659b538887b310477e8581c8fbcec93b407c1b9ba04a7c8c05d060a33eb7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2acaff560bbda5741538528a2967355ec86a8f7564adba0b2316989c66892374"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "0a4d0034c5a1379d5aa57c0a104aaa2adbb98f1e2b89d4ec0b7ef68df2e16a1a"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2e082857985c7550efdad38a1997b9805051b07fb61b0cd30921e786a8521130"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "6f6ecb72aa956a4461add613a717d751879092c6ef30bf1e4c8576e165324da6"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "2b7e219bada386ccaef89cfc13e67a0f8420728d73bfb8519f27b8c96615182b"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "8e5f6550359e71ecbea95705ec61fb03313550e6f481cabf48043929909aabae"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "ca7aaf32075a904c16620da9892290c28b10abba05673fa30781422393b02a6a"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "9f511e824978b45d8d90244e921dafcbb9bc01d1e4aced66afac71740ffa5ff6"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "4485332b8ff7be999cc4142ecad55763acdb587df69f748170bf5644f72d5729"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "9e2b351f3cabb1252259f5383e6f2fec3e3d90534dbecddef4ed183eba42f35a"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "3a4e194e945214cc457178f48e65b9ab6a8201b6d15b9736cd673324b70b6edd"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "78e6623084bd14f68ef1335ae8a419238c4119188b90fd9e71faf45c4f049942"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "65cd00e90de065e99d13352fd5d8aa3bc28d062b9dc935cf1da914a2047b2208"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "97e7fb0bf5c563366b7c6121fa2decb67597107e5594932c6a098cccc980629e"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "e5125f8f2709fd20f8182fade3d7f9e7129872c63f042c5489c6eba4733b6b49"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "d6f2fdcf0f4bc67dccd8e036f7c8117ffd76a008bd50e2a060cd23671ef9abb9"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "c34ad41e351235b1ca8e026e9fba9b3ee01c42e4933b060f0c870aac3014403a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "e39fea44e8f1b91ef0825d7ddfe1b5da7173439c1b23a4291c46542d2c39330c"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c3c06a4839ecfd4717686f7394396a4fc66b7a2e8eabbdd51f23ab2a1099cc1e"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "652900870d343dda5683456934ca76bf176ea54da73d9883d8a13c9b3cae2fac"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "ce3a430c123ff460df270c3387820330819cf31fef5ed3cfb0411f82c0357e82"
metafile = true

[[files]]
file = "mods/leave-my-bars-alone.pw.toml"
hash = "6fc46d72336be11582b933177410f6e0e1e89c5464e19a1885c5ce80738b01c5"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "6917553073df67745da1d535cc6107839a76b54081b1b6f368a38c723f5fd8c7"
metafile = true

[[files]]
file = "mods/library-ferret.pw.toml"
hash = "599c8c37e60b9f1fbfb29d10eb9ede3d174b72287b9fbe407e90b6417a27a441"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/lithosphere.pw.toml"
hash = "aeba47c6bee62a0fac3055bea3c132081cca21dd6d3d30fae562394cb1be3bee"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "a859b2f6265d5160e052d00659e4bf2ec3e307856c707110caaf9f83439c9f2c"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "54027603401c42860c29864e4e5e8639516743d2f3d17e51153fd841ffd58f5c"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6f0dcbcffd4400c6cef07f1eeb48cdc25bac0fa01270936feab4c549aff4738e"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "748bdcbc7788a77881979189827f1baf3f6ef5fdaeb58b00e51e043c2c0abe39"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "b3e831b3e4d6ddbf23806b0fec6087eca264af1ebc04e747c89024972aaa8607"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "758a6e0ca20802b83c96762c6399f7cd107c65260b2330373d46d7fddb69056e"
metafile = true

[[files]]
file = "mods/overflowing-bars.pw.toml"
hash = "cb40fc0e1e0a3338d57b34a5ba2612ae9a9f0e32619695c4da637a98b4e52cf3"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "0311ca22213f4a9c8fb943619271944d3ffedf7a17f098e8c0f8fad8f897d700"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "35ecf5a8ecf2d7b1a2b79f5d24a093e21d23f12486dcd71689894758d2fbe832"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "3bc82b2c795f11b9cda1e6aefc6d95cafeb5c1f702be1c9af711094babe0a2f6"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "18a8e2fb290df026bdb8a1022c5209afc851cddf9253631d179bf4c225b120f7"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "c1e526d3d17cb3563e596d45c7567ed1fe60c31bdc3457f7a747ef8150bd3c1b"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "c83dd1d3c2dde6081e6f89246fb3b89fa29734f5329f4cd6d949a5c0da55f35c"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium-options-mod-compat.pw.toml"
hash = "cef2df389d9ea783c940ff614e987223aa10b7653f8228d2f899071a151d60f6"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "347cac2ed12c9bc0561b6a59eeb4c121b10e5f3f71d54e9bf8d1343af57ef5b8"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "819b3e7402252905b6fe89743589df910c84995e8305995cb61d1f32fda2a2eb"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "a122640a4332366ca18ba14457dab9bba90e850c669e8e41270917ad0585756a"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "1f16e313b26943798db29ff44ada73cc4a519c0dedd623fa11789d396fcf21b0"
metafile = true

[[files]]
file = "mods/tool-trims.pw.toml"
hash = "79d04d954184defd602ce8e5258a1179b45664729d727d5d53e2c1693f05dd00"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "fcc4e00f37493f6292af7fbef7be6ea27e1a0cb4185d010e17db67e4ac61da15"
metafile = true

[[files]]
file = "mods/wwoo.pw.toml"
hash = "1960c304ef7e5eb391934e0c102fd3346afe586cd5df5efb0cd7235e0a583634"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "434ac58bf0c398eb06d03856a3de1edf30aba72ff11ac953bda99e34132c0376"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "b96abadb2cdb56d53145609e6a8ee9fd70171878bb5414412dddee1fca902a7b"
metafile = true

[[files]]
file = "resourcepacks/unique-dark.pw.toml"
hash = "ce2d08eee941ab5f68409acd583edb905b86e81b4a23cd5e8de0a99daefbef9f"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "c8cf0916fb1562623afbe55df9d8451097fb15e11a09121cdadd714c982a4494"
metafile = true
